### ISSUE TITLE
Minor issue: error message in SOURCE CONTROL view

### ISSUE THREAD

**Issue by hzwar** [sukumo28/vscode-audio-preview#33]
VS Code shows these errors when selecting changed audio files. No big deal but a bit annoying to click them away.

![image](https://user-images.githubusercontent.com/36644475/160247252-4f6b4cbe-fdc2-4b41-8c7a-e74a574e3653.png)

**Comment by sukumo28** [comment]
Thank you for reporting.

This message is shown when you try to open broken audio file.  
So I think your change broke audio file.  
In that case, I want to notify users that the file you try to open is broken.  
But 3 messages is too many, so I will reduce this to single message or show message in webview.  

If this message is shown for valid audio file, please tell me step to reproduce. 
In my environment, updating valid file to valid file does not cause this error.

**Comment by sukumo28** [comment]
From v2.03, only one error message is displayed when you open broken file.  
thank you!
