### ISSUE TITLE
improve remote decoding performance

### ISSUE THREAD

**Issue by faroit** [sukumo28/vscode-audio-preview#35]
i really love this extension and I use a lot throughout my daily work. Before I start explaining the issue, i have to admit that I do not know enough about the vscode extension mechanics so please correct me.

### Issue

when using the extension on a remote host (through the ssh extension), audio loading is very very slow. 

### Assumptions

the wasm based decoder is running in the host os and decodes the audio, eg. a compressed mp3. Then the decoded audio stream is send to the local vscode ui for playback. This results in very slow loading speed as the uncompressed audio will have to tunneled via ssh.

### Potential solution

would it be possible to decode the audio in the frontend and just send the file to the local ui for decoding there?

**Comment by hendriks73** [comment]
+1. Facing the same issue.

**Comment by sukumo28** [comment]
Thank you!
I will check this problem.

**Comment by sukumo28** [comment]
This issue has been resolved in v2.0.6 and will be closed.

**Comment by faroit** [comment]
@sukumo28 Awesome. Thanks
