### ISSUE TITLE
Will you consider adding log mel spectrogram or filter bank spectrogram?

### ISSUE THREAD

**Issue by LingweiMeng** [sukumo28/vscode-audio-preview#36]
Thanks so much for sharing this excellent tool.
Will you consider adding log mel spectrogram or filter bank spectrogram? 
This will help audio researchers.

**Comment by sukumo28** [comment]
Thank you for your good idea.
I would like to add it in the future.

However, I want to clean up the code before adding new features.

**Comment by ivallesp** [comment]
I would also be strongly interested! Happy to help if needed

**Comment by sukumo28** [comment]
v2.1.0 supports log and mel spectrograms.
