### ISSUE TITLE
NotSupportedError for certain audio files.

### ISSUE THREAD

**Issue by stonelazy** [sukumo28/vscode-audio-preview#37]
For certain Audio files am facing below issue
```
failed to prepare:NotSupportedError: Failed to execute 'createBuffer' on 'BaseAudioContext': The number of frames provided (0) is less than or equal to the minimum bound (0).
```   
Sample audio throwing this error can be found [here](https://workdrive.zohoexternal.com/external/cd558cb191b9259905c9be38c681317770384ea89aaa76588426a4f0e82f9c4f)

Problem:   
<img width="816" alt="image" src="https://user-images.githubusercontent.com/11377834/176384651-3588a276-4d4f-4353-8235-6c7a3a2b6cc7.png">

Host machine config: MacOS Monterey Apple M1 14 inch.

**Comment by stonelazy** [comment]
I just tried playing it using the link I had mentioned. If WorkDrive can't play it, can you pls download it in to your local machine and try it once ?

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/11377834/176575525-b275358f-e31a-44fe-ade9-40a942a26407.png">

**Comment by sukumo28** [comment]
In current implementation, float64 (double) does not supported.  
But WASM decoder contain decoder for pcm_float64le.  
So all I need to do may be fixing my decoder code.  
I will fix it. Thank you for reporting.

**Comment by sukumo28** [comment]
dbl is supported from v2.0.4~
thank you!
