### ISSUE TITLE
Why this mp3 can't be openned? is that a bug?

### ISSUE THREAD

**Issue by JackyZhangFuDan** [sukumo28/vscode-audio-preview#42]
http://online1.kkabc.com/voaspe/2022/20221006sa_science.mp3

**Comment by JackyZhangFuDan** [comment]
more information:
If we download some other mp3 from the same website, they are able to work, for example http://online2.kkabc.com/lesson/shi0529/0008/8998/20221101AsItIs01.mp3

above one is single channel, but the fail one is two channel (stereo) mp3, can that be root cause? 

Also, I tried to run your extension locally, compile your cpp with FFMpeg 4.3.5, the extension can't work too, same error

**Comment by sukumo28** [comment]
Sorry, this was a bug, and fixed recently.
Please update.
