### ISSUE TITLE
WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by quancs** [sukumo28/vscode-audio-preview#49]
Hello, this plugin reports the following errors, after I opening/playing/closing wavs serveral times.
```
Cannot read properties of undefined (reading 'readAudioInfo')
Aborted(RangeError: WebAssembly.instantiate(): Out of memory: wasm memory). Build with -sASSERTIONS for more info.
```

**Comment by sukumo28** [comment]
Sorry, this doesn't happen in my environment.
Please try updating as it may have been unintentionally fixed in some version.
If the problem still occurs, please open the issue again.
