### ISSUE TITLE
failed to decode audio: -48: avcodec_send_packet: Out of memory

### ISSUE THREAD

**Issue by rakkarage** [sukumo28/vscode-audio-preview#52]
thanks. idk

works: pcm_s16le
https://github.com/rakkarage/Interface/blob/main/Audio/170141__timgormly__8-bit-bump.wav

![1](https://github.com/sukumo28/vscode-audio-preview/assets/962340/4d2c50a5-1ed4-4ee2-aae3-5d5579cf691e)

not works: pcm_s24le
https://github.com/rakkarage/Interface/blob/main/Audio/257357__brnck__button-click.wav

![2](https://github.com/sukumo28/vscode-audio-preview/assets/962340/7e3bb276-89a1-4c47-a4ee-f79632d9de67)

`failed to decode audio: -48: avcodec_send_packet: Out of memory`

![3](https://github.com/sukumo28/vscode-audio-preview/assets/962340/38e56627-271f-4bf4-b736-a7506890ba92)

**Comment by daseulll** [comment]
I face the same issue when playing an MP3 file. There is no trouble with WAV, ACC, or FLAC.
(macOS catalina 10.15.7)

**Comment by khood5** [comment]
same problem for me I am running a mix (Windows 11/ MacOS) client with remote dev on linux (ubuntu) some files work great other do not. The files that dont are shorter if that makes any difference

**Comment by sukumo28** [comment]
This issue is probably resolved in v2.0.6, so I'll close it.
